version: "3.5"

services:
  yolo.app:
        image: tytye/yolo-app:latest
        container_name: yolo-app
        stdin_open: true
        command: npm run dev 
        ports:
          - "3000:3000"
          - "5001:5001"
        volumes:
          - "./client:/var/www/client"
          - "./backend:/var/www/backend"
        networks:
          - yolo_net
        env_file:
          - ./.env
networks:
  yolo_net:
    driver: bridge
    name: yolo_net
