apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
immutable: false 
data:
  username: YWRtaW51c2Vy #adminuser 
  mongodb.conf: |  # Defines the content of the MongoDB configuration file
    storage:
      dbPath: /data/db  # Sets the MongoDB data storage path
    replication:
      replSetName: "rs0"