apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-app
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: yolo-app
  template:
    metadata:
      labels:
        app: yolo-app
    spec:
      containers:
        - name: yolo-app
          image: tytye/yolo-app:latest
          ports:
            - containerPort: 3000
            - containerPort: 5001
          resources:
            limits:
              cpu: "750m" # 0.75 vCPUs
              memory: "1500Mi" # 1.5 GB RAM
            requests:
              cpu: "350m" # Request 0.5 vCPUs
              memory: "500Mi" # Request 1 GB RAM
