apiVersion: v1
kind: Service
metadata:
  name: yolo-app-service
spec:
  type: NodePort
  selector:
    app: yolo-app
  ports:
    - nodePort: 31317
      port: 3000
      targetPort: 3000
      protocol: TCP
      
