apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-app
spec:
  replicas: 3
  minReadySeconds: 10  # Pod should be ready for at least 10 seconds before being considered available
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1  # Ensures at least 2 pods are always available during updates
      maxSurge: 1        # Allows one extra pod to be created during updates
  selector:
    matchLabels:
      app: yolo-app
  template:
    metadata:
      labels:
        app: yolo-app
    spec:
      containers:
        - name: yolo-app
          image: tytye/yolo-app:latest
          ports:
            - containerPort: 3000
            - containerPort: 5001
          env:
            - name: REACT_APP_BACKEND_API_URL
              value: "http://yolo-app-service:5001"
          resources:
            limits:
              cpu: "200m"
              memory: "512Mi"
            requests:
              cpu: "50m"
              memory: "256Mi"
