apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yolo-app
  template:
    metadata:
      labels:
        app: yolo-app
    spec:
      containers:
        - name: yolo-app
          image: tytye/yolo-app:latest
          ports:
            - containerPort: 3000 
            - containerPort: 5001 
          env:
            - name: REACT_APP_BACKEND_API_URL
              value: "http://yolo-app-service:5001"
          resources:
            limits:
              cpu: "0.5"    
              memory: "512Mi"  
            requests:
              cpu: "0.1"  
              memory: "256Mi"  # 