apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-app
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: yolo-app
  template:
    metadata:
      labels:
        app: yolo-app
    spec:
      containers:
        - name: yolo-app
          image: tytye/yolo-app:latest
          ports:
            - containerPort: 3000
            - containerPort: 5001
          resources:
            limits:
              cpu: "200m"
              memory: "512Mi"
            requests:
              cpu: "50m"
              memory: "256Mi"
