apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-app
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: yolo-app
  template:
    metadata:
      labels:
        app: yolo-app
    spec:
      initContainers:
      - name: init-env
        image: appropriate/curl # Use an image that has curl or wget installed
        command: ["sh", "-c", "EXTERNAL_IP=$(kubectl get svc yolo-app-service -o=jsonpath='{.status.loadBalancer.ingress[0].ip}') && echo \"REACT_APP_BACKEND_API_URL=http://$EXTERNAL_IP\" > /usr/src/app/.env"]
        volumeMounts:
        - name: app-volume
          mountPath: /usr/src/app/.env
      containers:
      - name: yolo-app
        image: tytye/yolo-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_BACKEND_API_URL
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: REACT_APP_BACKEND_API_URL
        resources:
          limits:
            cpu: "200m"
            memory: "512Mi"
          requests:
            cpu: "50m"
            memory: "256Mi"
      volumes:
      - name: app-volume
        emptyDir: {}
