name: Build and Deploy to GKE

on:
  push:
    branches: [ k8-gke-deployment ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: yolo-cluster   
  GKE_ZONE: us-central1  
  DEPLOYMENT_NAME: yolo-deployment

jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        id: build
        run: |
          IMAGE_TAG="v$(date +'%y.%m.%d.%H')"
          docker login -u tytye -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker buildx build --platform linux/amd64,linux/arm64 -t tytye/yolo-app:$IMAGE_TAG -t tytye/yolo-app:latest . --push

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: publish-image
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Configure Workload Identity Federation and generate an access token.
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY }}'

    # Get the GKE credentials so we can deploy to the cluster
    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}


    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        kubectl apply -f charts/
        # kubectl rollout status deployment/$DEPLOYMENT_NAME
        kubectl get services -o wide
