name: Build and publish app image
on:
  workflow_dispatch:

jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        run: |
          IMAGE_TAG="tytye/yolo-app:$(date +'%Y%m%d%H%M%S')"
          docker build . -t $IMAGE_TAG
      - name: publish
        run: |
          docker login -u tytye -p ${{secrets.DOCKER_HUB_TOKEN}}
          docker push $IMAGE_TAG
