name: Build and publish app image
on:
  workflow_dispatch:

jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        run: |
          export IMAGE_TAG="v$(date +'%y.%m.%d.%H')"
          echo $IMAGE_TAG
          # docker build . -t tytye/yolo-app:$IMAGE_TAG
      - name: publish
        run: |
          echo $IMAGE_TAG
          # docker login -u tytye -p ${{secrets.DOCKER_HUB_TOKEN}}
          # docker push tytye/yolo-app:$IMAGE_TAG
