name: Build and publish app image
on: [workflow_dispatch]

jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        run: |
          docker build . -t tytye/yolo-app:latest
      - name: publish
        run: |
          docker login -u tytye -p ${{secrets.DOCKER_HUB_TOKEN}}
          docker push tytye/yolo-app:latest
